### ISSUE TITLE
Extend built in types properties

### ISSUE THREAD

**Issue by neriyaco** [xpodev/extypes#6]
It would be very nice if we'll have an option to extend the properties of built in types as well.

Example:
```py
class ListExtension(list):
    @extension
    @property
    def length(self):
        return len(self)


extend_type_with(list, ListExtension)

a = list(range(10))
print(a.length)
```

Currently the module raises a `TypeError` as the property is not callable
```py
def extension(fn: _T) -> _T:
    if not callable(fn): # <-- Here
        raise TypeError
    fn._extension_method = True
    return fn
```

**Comment by neriyaco** [comment]
I think, if the `@extension` decorator is applied to a method / property it should be added to the type, whether it's a property or a method.

**Comment by binyamin555** [comment]
> Should we check for a `property`, or for a general descriptor?
> We can test if the given object has a `__get__` method. Is that enough? Is that correct?
> https://docs.python.org/3/howto/descriptor.html#id12

Yes, any class which define one of the `__get__`, `__set__` or `__delete__` is a descriptor.

Also, we should call the `__set_name__` method on any extension that defines this method, even for non-descriptor objects (as said in the Python documentation).


This is the relevant information for implementing descriptor extensions.
[descriptor protocol](https://docs.python.org/3/howto/descriptor.html#id15)

**Comment by binyamin555** [comment]
Fixed
